swagger: '2.0'
info:
  title: Zamaszama Api
  description: The easiest way to order food anywhere you are
  version: "1.0.0"
host: "localhost:3000"
schemes:
  - https
  - http
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
paths:
  /login:
    post:
      summary: User authorization and create token
      description: |
        Return token used by the client with each request made to the server. If token is not valid the response will be 401.
      parameters:
        - name: login
          in: query
          description: User login
          required: true
          type: string
        - name: password
          in: query
          description: User password
          required: true
          type: string
      tags:
        - Authentication
      responses:
        200:
          description: Successful request.
          schema:
            $ref: "#/definitions/UserSessionInfo"
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /currentOrder:
    get:
      summary: Retrive users current order
      description: Retrive users current order
      responses:
        200:
          description: User current order
          schema:
            $ref: '#/definitions/Order'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      tags: 
        - User order
    
definitions:
  UserSessionInfo:
    properties:
      name: 
        type: string
        desciption: Logged user name
      email: 
        type: string
        description: Email
      role: 
        type: string
        enum:
          - USER
          - ADMIN
        description: user role
      token:
        type: string
        description: token
      needChangePassword:
        type: boolean
        description: Need change password
  User:
    properties:
      name:
        type: string
        description: Name.
      email:
        type: string
        description: Email.       
      needChangePassword:
        type: boolean
        description: Need change password.
  Order:
    properties:
      user:
        $ref: '#/definitions/User'
      date:
        type: string
        description: Date.  
      meals:
        type: array
        items:
          $ref: '#/definitions/Meal'
          minItems: 0
          uniqueItems: true  

  Meal:
    properties:
      type:
        type: string
        description: Type.      
      name:
        type: string
        description: Name.   
      amount:
        type: string
        description: Amount.   
      company:
        type: string
        description: Company.           
        
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
